# Generated by Django 2.2.2 on 2019-08-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id_domain', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(default='No information available', max_length=200)),
            ],
        ),
    ]
