# Generated by Django 2.2.2 on 2019-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('rut', models.IntegerField(max_length=8)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('E', 'Empaque'), ('E', 'Reemplazo')], max_length=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('V', 'Vacaciones'), ('S', 'Suspendido'), ('E', 'Eliminado')], max_length=1)),
                ('telefono', models.CharField(max_length=12)),
                ('cant_turnos_disponibles', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
