# Generated by Django 2.2.2 on 2019-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0002_auto_20190829_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cant_turnos_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(),
        ),
    ]
