# Generated by Django 2.2.2 on 2019-08-29 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EMPAQUES', '0006_auto_20190829_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id_Anuncios', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_anotaciones',
            fields=[
                ('id_Categoria_anotaciones', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('nombre_anotacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('E', 'Empaque'), ('E', 'Reemplazo')], max_length=1)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrera', models.CharField(max_length=200)),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('V', 'Vacaciones'), ('S', 'Suspendido'), ('E', 'Eliminado')], max_length=1)),
                ('telefono', models.CharField(max_length=12)),
                ('cant_turnos_disponibles', models.IntegerField()),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Universidades')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_Turnos', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('usuario', models.ManyToManyField(blank=True, to='EMPAQUES.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_de_Espera',
            fields=[
                ('id_Lista_de_Espera', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Universidades')),
            ],
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id_Finanzas', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_Comentarios', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('contenido', models.TextField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Anuncios')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anuncios',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Usuario'),
        ),
        migrations.CreateModel(
            name='Anotaciones',
            fields=[
                ('id_Anotaciones', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('turnos_restados', models.IntegerField()),
                ('categoria_anotaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Categoria_anotaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPAQUES.Usuario')),
            ],
        ),
    ]
