# Generated by Django 2.2.2 on 2019-09-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0007_auto_20190829_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='anuncio',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='finanzas',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='lista_de_espera',
            name='universidad',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='universidad',
        ),
        migrations.DeleteModel(
            name='Anotaciones',
        ),
        migrations.DeleteModel(
            name='Anuncios',
        ),
        migrations.DeleteModel(
            name='Categoria_anotaciones',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Finanzas',
        ),
        migrations.DeleteModel(
            name='Lista_de_Espera',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
