# Generated by Django 2.2.2 on 2019-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0014_auto_20190918_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='EMPAQUES/static/media/perfil/default.png', upload_to='perfil/'),
        ),
    ]
