# Generated by Django 2.1.8 on 2019-10-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0015_auto_20190918_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toma_turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ('fecha', 'hora_inicio', 'hora_final')},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='perfil/default.png', upload_to='perfil/'),
        ),
    ]
