# Generated by Django 3.0.4 on 2020-03-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0017_anotaciones_fecha_termino_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='toma_turnos',
            name='lugar_reunión',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
