# Generated by Django 3.0.4 on 2020-03-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0018_toma_turnos_lugar_reunión'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toma_turnos',
            old_name='lugar_reunión',
            new_name='lugar_reunion',
        ),
    ]
