# Generated by Django 3.0.4 on 2020-03-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0019_auto_20200329_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toma_turnos',
            name='fecha_termino',
        ),
    ]
