# Generated by Django 3.0.4 on 2020-03-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0020_remove_toma_turnos_fecha_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje_inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
