# Generated by Django 3.0.4 on 2020-03-30 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EMPAQUES', '0021_mensaje_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje_inicio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
